apiVersion: v2
version: 4.0.2
appVersion: "v4.0.2"
description: Helm chart for Mojaloop Payment Manager
name: mojaloop-payment-manager
maintainers:
  - name: James Bush
    email: james.bush@modusbox.com
  - name: David Fry
    email: david.fry@modusbox.com
