apiVersion: v2
version: 2.7.1
appVersion: "v2.7.1"
description: Helm chart for Mojaloop Payment Manager
name: mojaloop-payment-manager
maintainers:
  - name: James Bush
    email: james.bush@modusbox.com
