apiVersion: v2
version: 3.0.0
appVersion: "v3.0.0"
description: Helm chart for Mojaloop Payment Manager
name: mojaloop-payment-manager
maintainers:
  - name: James Bush
    email: james.bush@modusbox.com
