apiVersion: v2
version: 9.0.2
appVersion: "v4.2.14"
description: Helm chart for Mojaloop Payment Manager
name: mojaloop-payment-manager
maintainers:
  - name: James Bush
    email: james.bush@modusbox.com
  - name: David Fry
    email: david.fry@modusbox.com
dependencies:
  - name: pm4ml-ui
    version: 1.14.1
    repository: file://../pm4ml-ui
    alias: frontend
    condition: frontend.enabled
  - name: pm4ml-experience-api
    version: 1.8.22
    repository: file://../pm4ml-experience-api
    alias: experience-api
    condition: experience-api.enabled
  - name: pm4ml-management-api-service
    version: 2.0.2
    repository: file://../pm4ml-management-api-service
    alias: management-api
    condition: management-api.enabled
  - name: redis
    version: 17.6.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: sdk-scheme-adapter
    version: 1.0.0
    repository: http://mojaloop.io/helm/repo
    alias: scheme-adapter
    condition: scheme-adapter.enabled
  - name: mojaloop-core-connector
    version: 1.1.2
    repository: file://../mojaloop-core-connector
    condition: mojaloop-core-connector.enabled
  - name: prometheus
    version: 11.16.9
    repository: https://prometheus-community.github.io/helm-charts
    alias: prometheus
  - name: vault
    version: 0.14.0
    repository: https://helm.releases.hashicorp.com
    alias: vault
    condition: vault.enabled
  - name: ml-testing-toolkit
    version: 15.4.0
    repository: http://mojaloop.io/helm/repo
    alias: ttk
    condition: ttk.enabled
  - name: keycloak
    version: 10.3.0
    repository: https://codecentric.github.io/helm-charts
    alias: keycloak
    condition: keycloak.enabled
  - name: sim-backend
    version: 1.0.5
    repository: file://../mojaloop-simulator-backend
    condition: sim-backend.enabled
  - name: common
    version: 1.x.x
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
