apiVersion: v1
version: 2.4.0
appVersion: "v2.4.0"
description: Helm chart for Mojaloop Payment Manager
name: mojaloop-payment-manager
maintainers:
  - name: James Bush
    email: james.bush@modusbox.com
