apiVersion: v1
version: 2.0.4
appVersion: "v2.0.4"
description: Helm chart for Mojaloop Payment Manager
name: mojaloop-payment-manager
maintainers:
  - name: James Bush
    email: james.bush@modusbox.com
