apiVersion: v1
version: 2.3.0
appVersion: "v2.3.0"
description: Helm chart for Mojaloop Payment Manager
name: mojaloop-payment-manager
maintainers:
  - name: James Bush
    email: james.bush@modusbox.com
