apiVersion: v2
version: 2.9.3
appVersion: "v2.9.3"
description: Helm chart for Mojaloop Payment Manager
name: mojaloop-payment-manager
maintainers:
  - name: James Bush
    email: james.bush@modusbox.com
