apiVersion: v2
version: 2.6.0
appVersion: "v2.6.0"
description: Helm chart for Mojaloop Payment Manager
name: mojaloop-payment-manager
maintainers:
  - name: James Bush
    email: james.bush@modusbox.com
