apiVersion: v1
version: 2.1.3
appVersion: "v2.1.3"
description: Helm chart for Mojaloop Payment Manager
name: mojaloop-payment-manager
maintainers:
  - name: James Bush
    email: james.bush@modusbox.com
