# requirements.yaml
dependencies:
- name: pm4ml-ui
  version: 1.8.9
  repository: file://../pm4ml-ui
  alias: frontend
  condition: frontend.enabled
- name: pm4ml-experience-api
  version: 1.8.15
  repository: file://../pm4ml-experience-api
  alias: experience-api
  condition: experience-api.enabled
- name: pm4ml-management-api-service
  version: 1.9.1
  repository: file://../pm4ml-management-api-service
  alias: management-api
  condition: management-api.enabled
- name: redis
  version: 10.7.16
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
- name: pm4ml-mojaloop-connector
  version: 1.2.3
  repository: file://../pm4ml-mojaloop-connector
  condition: pm4ml-mojaloop-connector.enabled
- name: mojaloop-simulator-core-connector
  version: 1.3.4
  repository: file://../mojaloop-simulator-core-connector
  condition: mojaloop-simulator-core-connector.enabled
- name: mojaloop-mifos-core-connector
  version: 1.0.0
  repository: file://../mojaloop-mifos-core-connector
  condition: mojaloop-mifos-core-connector.enabled
- name: prometheus
  version: 11.16.9
  repository: https://prometheus-community.github.io/helm-charts
  alias: prometheus
- name: ml-testing-toolkit
  version: 11.0.0
  repository: http://mojaloop.io/helm/repo
  alias: ttk
  condition: ttk.enabled
- name: keycloak
  version: 10.3.0
  repository: https://codecentric.github.io/helm-charts
  alias: keycloak
  condition: keycloak.enabled
- name: sim-backend
  version: 1.0.0
  repository: file://../mojaloop-simulator-backend
  condition: sim-backend.enabled
