{{- $fullName := include "self.fullname" . -}}
{{- $labels := include "self.labels" . -}}
{{- range $secretName, $secretValue := .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-{{ $secretName }}
  labels:
{{ $labels | indent 4 }}
data:
{{- range $k, $v := $secretValue }}
  {{ $k | quote }}: {{ $v | b64enc }}
{{- end }}
---
{{- end }}
