apiVersion: v2
version: 1.8.26
appVersion: "v3.1.0"
description: A Helm chart for Kubernetes
name: pm4ml-experience-api
maintainers:
  - name: Murthy Kakarlamudi
    email: murthy@modusbox.com
  - name: Nguni Phakela
    email: nguni@izyane.com
