apiVersion: v2
version: 1.8.23
appVersion: "2.0.6"
description: A Helm chart for Kubernetes
name: pm4ml-experience-api
maintainers:
  - name: Murthy Kakarlamudi
    email: murthy@modusbox.com
  - name: Nguni Phakela
    email: nguni@izyane.com
  