apiVersion: v1
kind: Service
metadata:
  name: sim-backend
  labels:
    {{- include "sim-backend.common-labels" $ | nindent 4 }}
spec:
   type: ClusterIP
   ports:
   - port: 3000
     protocol: TCP
     name: simapi
     targetPort: simapi
   - port: 3002
     protocol: TCP
     name: reportapi
     targetPort: reportapi
   - port: 3003
     protocol: TCP
     name: testapi
     targetPort: testapi
   selector:
      {{- include "sim-backend.common-labels" $ | nindent 6 }}
