{{- if .Values.testIngress.enabled -}}
{{- $fullName := include "mojaloop-payment-manager-proxy.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-test-ingress
  labels:
{{ include "mojaloop-payment-manager-proxy.labels" . | indent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  {{- with .Values.testIngress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.testIngress.tls }}
  tls:
  {{- range .Values.testIngress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.testIngress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /mgmt-api-scheme-1(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $.Values.testIngress.mgmtApiScheme1ServiceName }}
                port:
                  name: testapi
          - path: /mgmt-api-scheme-2(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $.Values.testIngress.mgmtApiScheme2ServiceName }}
                port:
                  name: testapi
          - path: /proxy-adapter(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $.Values.testIngress.proxyAdapterServiceName }}
                port:
                  name: testapi
  {{- end }}
{{- end }}
