apiVersion: v2
version: 0.0.1.5
appVersion: "v0.0.1"
description: Helm chart for Interscheme Proxy Adapter
name: interscheme-proxy-adapter
maintainers:
  - name: Steven Oderayi
    email: steven.oderayi@infitx.com
dependencies:
  - name: interscheme-proxy-adapter
    version: 0.0.1
    repository: file://../interscheme-proxy-adapter
    alias: interscheme-proxy-adapter
    condition: interscheme-proxy-adapter.enabled
  - name: management-api-service
    version: 2.0.2
    repository: file://../pm4ml-management-api-service
    alias: management-api
    condition: management-api-base.enabled
  - name: ml-testing-toolkit
    version: 17.4.0
    repository: http://mojaloop.io/helm/repo
    alias: ttk
    condition: ttk.enabled
