apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-pm4ml-ui
  labels:
    app.kubernetes.io/name: pm4ml-ui
    helm.sh/chart: pm4ml-ui-1.0.0
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pm4ml-ui
      app.kubernetes.io/instance: test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pm4ml-ui
        app.kubernetes.io/instance: test
    spec:
      imagePullSecrets:
        - name: pm4ml-ui-cred
      containers:
        - name: pm4ml-ui
          image: "modusbox-mbx-docker.jfrog.io/modusintegration/payment-manager-ui:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: "MOCK_DATA"
              value: "false"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
