apiVersion: v1
kind: Service
metadata:
  name: {{ include "mojaloop-payment-token-adapter.fullname" . }}
  labels:
{{ include "mojaloop-payment-token-adapter.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.portalPort }}
      protocol: TCP
      name: portal
      targetPort: portal
    - port: {{ .Values.service.sdkPort }}
      protocol: TCP
      name: sdk
      targetPort: sdk
  selector:
    app.kubernetes.io/name: {{ include "mojaloop-payment-token-adapter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
