apiVersion: v1
kind: Service
metadata:
  name: {{ include "pm4ml-management-api-service.fullname" . }}
  labels:
{{ include "pm4ml-management-api-service.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.env.CONTROL_LISTEN_PORT }}
      protocol: TCP
      name: control
    {{- if .Values.env.ENABLE_TEST_API }}
    - port: {{ .Values.env.TEST_API_PORT }}
      protocol: TCP
      name: testapi
      targetPort: testapi
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "pm4ml-management-api-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
