apiVersion: v2
version: 0.0.1
appVersion: "0.0.1"
description: Helm chart for Inter scheme Proxy Adapter
name: inter-scheme-proxy-adapter
maintainers:
  - name: Steven Oderayi
    email: steven.oderayi@infitx.com
  - name: Vijaya Kumar Guthi
    email: vijaya.guthi@infitx.com
dependencies:
  - name: common
    repository: "https://mojaloop.github.io/charts/repo"
    tags:
      - moja-common
    version: 3.0.0
