{{- if .Values.imagePullCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pm4ml-mojaloop-connector.fullname" . }}-cred
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "pm4ml-mojaloop-connector.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}