{{- if .Values.env.JWS_SIGN }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pm4ml-mojaloop-connector.fullname" . }}-jws-priv-key
  labels:
    app.kubernetes.io/name: {{ include "pm4ml-mojaloop-connector.fullname" . }}-jws-priv-key
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/version: "{{ $.Chart.AppVersion }}"
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
data:
  # Note that due to a bug with helm 2.9.1 the `required` function in combination with a missing
  # key will not work in place of this if statement.
  {{- if eq .Values.secrets.jws.privateKey "" }}
    {{ fail (printf "JWS_SIGN enabled- JWS private key required for %s. You need to specify %s.secrets.jws.privateKey." .Values.env.DFSP_ID .Values.env.DFSP_ID) }}
  {{- end }}
  "private.key": {{ .Values.secrets.jws.privateKey | b64enc }}
---
{{- end }}
