# Default values for mojaloop-simulator-core-connector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: pm4ml/mojaloop-payment-manager-simulator-core-connector
  tag: 1.4.1
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

#### ENV values
env:
  LISTEN_PORT: 3002
  MLCONN_OUTBOUND_LISTEN_PORT: 4001
  outboundApplicationEndpoint: http://pm4ml-mojaloop-connector:4001
  FSP_BACKEND_LISTEN_PORT: 3000
  backendApplicationEndpoint: http://localhost:3002

service:
  type: ClusterIP
  coreConnector:
    port: 80
  mlConnOutbound:
    port: 4001
  fspBackend:
    port: 3000

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
