{{- if .Values.env.VISA_MLE_ENABLED }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mojaloop-visadirect-core-connector.fullname" . }}-mle-creds
  labels:
    app.kubernetes.io/name: {{ include "mojaloop-visadirect-core-connector.fullname" . }}-mle-creds
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/version: "{{ $.Chart.AppVersion }}"
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
data:
  {{- $requiredMessage := "MLE enabled- MLE private key and public key are required for message encryptioin and decryption. You need to specify secrets.mle.privateKey & secrets.mle.publicKey." }}
  "private_key.pem": {{ .Values.secrets.mle.privateKey | required $requiredMessage | b64enc }}
  "public_key.pem": {{ .Values.secrets.mle.publicKey | required $requiredMessage | b64enc }}
{{- end }}