apiVersion: v2
version: 0.0.1
appVersion: "0.0.1"
description: Helm chart for Interscheme Proxy Adapter
name: interscheme-proxy-adapter
maintainers:
  - name: Steven Oderayi
    email: steven.oderayi@infitx.com